name: contador
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  run_vite:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install Dependencies
        working-directory: clase18/contador
        run: npm install

      - name: Run Vite Build
        working-directory: clase18/contador
        run: npx vite build

      - name: Configurar github pages
      
      - name: save zip
        uses: actions/upload-pages-artifact@v4
        with:
          path: clase18/contador/dist
        uses: actions/configure-pages@v5
      - name: Publicar
        uses: actions/deploy-pages@v4
