name: serpiente

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  run_vite:
    runs-on: ubuntu-latest

    steps:
      - name: Download Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        working-directory: examen/serpiente
        run: npm install

      - name: Run Vite Build
        working-directory: examen/serpiente
        run: npx vite build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Guardar artefacto
        uses: actions/upload-pages-artifact@v4
        with:
          path: examen/serpiente/dist

      - name: Publicar
        uses: actions/deploy-pages@v4
